# yaml-language-server: $schema=../../src/asqi/schemas/asqi_suite_config.schema.json
suite_name: "Mock Tester Sanity Check"
test_suite:
  - id: "run_mock_on_compatible_sut"
    name: "run mock on compatible sut"
    image: "asqiengineer/test-container:mock_tester-latest"
    volumes:
      output: /workspaces/asqi/output 
    systems_under_test:
      - "openai_gpt4o_mini" # if using demo_suts, it should fail with other systems_under_test or my_backend_api
    params:
      delay_seconds: 1

