suite_name: "Inspect Knowledge Evaluation Suite"
test_suite:

  # AGIEval
  - id: "inspect_agie_aqua_rat"
    name: "inspect agie aqua rat"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_aqua_rat"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_logiqa_en"
    name: "inspect agie logiqa en"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_logiqa_en"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_lsat_ar"
    name: "inspect agie lsat ar"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_lsat_ar"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_lsat_lr"
    name: "inspect agie lsat lr"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_lsat_lr"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_lsat_rc"
    name: "inspect agie lsat rc"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_lsat_rc"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_math"
    name: "inspect agie math"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_math"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_sat_en"
    name: "inspect agie sat en"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_sat_en"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_sat_en_without_passage"
    name: "inspect agie sat en without passage"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_sat_en_without_passage"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agie_sat_math"
    name: "inspect agie sat math"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "agie_sat_math"
      evaluation_params: {}
      limit: 2

  # AIR Bench
  - id: "inspect_air_bench"
    name: "inspect air bench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "air_bench"
      evaluation_params: {}
      limit: 2

  # ChemBench
  - id: "inspect_chembench"
    name: "inspect chembench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "chembench"
      evaluation_params: {}
      limit: 2

  # CommonsenseQA
  - id: "inspect_commonsense_qa"
    name: "inspect commonsense qa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "commonsense_qa"
      evaluation_params: {}
      limit: 2

  # GPQA
  - id: "inspect_gpqa_diamond"
    name: "inspect gpqa diamond"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "gpqa_diamond"
      evaluation_params: {}
      limit: 2

  # HealthBench
  - id: "inspect_healthbench"
    name: "inspect healthbench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "healthbench"
      evaluation_params: {}
      limit: 2

  # Humanity's Last Exam
  - id: "inspect_hle"
    name: "inspect hle"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "hle"
      evaluation_params: {}
      limit: 2

  # LiveBench
  - id: "inspect_livebench"
    name: "inspect livebench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "livebench"
      evaluation_params: {}
      limit: 2

    # MMLU-Pro
  - id: "inspect_mmlu_pro"
    name: "inspect mmlu pro"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "mmlu_pro"
      evaluation_params: {}
      limit: 2

  - id: "inspect_mmlu_0_shot"
    name: "inspect mmlu 0 shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "mmlu_0_shot"
      evaluation_params: {}
      limit: 2

  - id: "inspect_mmlu_5_shot"
    name: "inspect mmlu 5 shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "mmlu_5_shot"
      evaluation_params: {}
      limit: 2

  # MedQA
  - id: "inspect_medqa"
    name: "inspect medqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "medqa"
      evaluation_params: {}
      limit: 2

  # O-NET
  - id: "inspect_onet_m6"
    name: "inspect onet m6"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "onet_m6"
      evaluation_params: {}
      limit: 2

  # Pre-Flight
  - id: "inspect_pre_flight"
    name: "inspect pre flight"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "pre_flight"
      evaluation_params: {}
      limit: 2

  # PubMedQA
  - id: "inspect_pubmedqa"
    name: "inspect pubmedqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "pubmedqa"
      evaluation_params: {}
      limit: 2

  # SOS BENCH
  - id: "inspect_sosbench"
    name: "inspect sosbench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "sosbench"
      evaluation_params: {}
      limit: 2

  # SciKnowEval
  - id: "inspect_sciknoweval"
    name: "inspect sciknoweval"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "sciknoweval"
      evaluation_params:
        domain: biology
        level: l4
      limit: 2

  # SimpleQA
  - id: "inspect_simpleqa"
    name: "inspect simpleqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "simpleqa"
      evaluation_params: {}
      limit: 2

  # TruthfulQA
  - id: "inspect_truthfulqa"
    name: "inspect truthfulqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "truthfulqa"
      evaluation_params: {}
      limit: 2

  # XSTest
  - id: "inspect_xstest"
    name: "inspect xstest"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "xstest"
      evaluation_params: {}
      limit: 2
