suite_name: "Inspect Personality Evaluation Suite"
test_suite:

  # Personality
  - id: "inspect_personality_BFI"
    name: "inspect personality BFI"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "personality_BFI"
      evaluation_params: {}
      limit: 2

  - id: "inspect_personality_TRAIT"
    name: "inspect personality TRAIT"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "personality_TRAIT"
      evaluation_params: {}
      limit: 2
