suite_name: "Inspect Reasoning Evaluation Suite"
test_suite:

  - id: "inspect_arc_challenge"
    name: "inspect arc challenge"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "arc_challenge"
      evaluation_params: {}
      limit: 2

  - id: "inspect_arc_easy"
    name: "inspect arc easy"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "arc_easy"
      evaluation_params: {}
      limit: 2

  # BBH
  - id: "inspect_bbh"
    name: "inspect bbh"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "bbh"
      evaluation_params: {}
      limit: 2

  # BIG-Bench Extra Hard
  - id: "inspect_bbeh"
    name: "inspect bbeh"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "bbeh"
      evaluation_params: {}
      limit: 2

  - id: "inspect_bbeh_mini"
    name: "inspect bbeh mini"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "bbeh_mini"
      evaluation_params: {}
      limit: 2

  # BoolQ
  - id: "inspect_boolq"
    name: "inspect boolq"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "boolq"
      evaluation_params: {}
      limit: 2

  # DROP
  - id: "inspect_drop"
    name: "inspect drop"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "drop"
      evaluation_params: {}
      limit: 2

  # HellaSwag
  - id: "inspect_hellaswag"
    name: "inspect hellaswag"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "hellaswag"
      evaluation_params: {}
      limit: 2

  # IFEval
  - id: "inspect_ifeval"
    name: "inspect ifeval"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "ifeval"
      evaluation_params: {}
      limit: 2

  # LingOly
  - id: "inspect_lingoly"
    name: "inspect lingoly"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "lingoly"
      evaluation_params: {}
      limit: 2

  - id: "inspect_lingoly_too"
    name: "inspect lingoly too"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "lingoly_too"
      evaluation_params: {}
      limit: 2

  # MMMU
  - id: "inspect_mmmu_multiple_choice"
    name: "inspect mmmu multiple choice"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "mmmu_multiple_choice"
      evaluation_params:
        subjects:
          - Computer_Science
      limit: 2

  - id: "inspect_mmmu_open"
    name: "inspect mmmu open"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "mmmu_open"
      evaluation_params:
        subjects:
          - Computer_Science
      limit: 2

  # MuSR
  - id: "inspect_musr"
    name: "inspect musr"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "musr"
      evaluation_params: {}
      limit: 2

  # Needle in a Haystack (NIAH)
  - id: "inspect_niah"
    name: "inspect niah"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "niah"
      evaluation_params: {}
      limit: 2

  # PAWS
  - id: "inspect_paws"
    name: "inspect paws"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "paws"
      evaluation_params: {}
      limit: 2

  # PIQA
  - id: "inspect_piqa"
    name: "inspect piqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "piqa"
      evaluation_params: {}
      limit: 2

  # RACE-H
  - id: "inspect_race_h"
    name: "inspect race h"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "race_h"
      evaluation_params: {}
      limit: 2

  # WINOGRANDE
  - id: "inspect_winogrande"
    name: "inspect winogrande"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "winogrande"
      evaluation_params: {}
      limit: 2

  # WorldSense
  - id: "inspect_worldsense"
    name: "inspect worldsense"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "worldsense"
      evaluation_params: {}
      limit: 2

  # âˆžBench
  - id: "inspect_infinite_bench_code_debug"
    name: "inspect infinite bench code debug"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_code_debug"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_code_run"
    name: "inspect infinite bench code run"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_code_run"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_kv_retrieval"
    name: "inspect infinite bench kv retrieval"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_kv_retrieval"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_longbook_choice_eng"
    name: "inspect infinite bench longbook choice eng"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_longbook_choice_eng"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_longdialogue_qa_eng"
    name: "inspect infinite bench longdialogue qa eng"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_longdialogue_qa_eng"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_math_calc"
    name: "inspect infinite bench math calc"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_math_calc"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_math_find"
    name: "inspect infinite bench math find"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_math_find"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_number_string"
    name: "inspect infinite bench number string"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_number_string"
      evaluation_params: {}
      limit: 2

  - id: "inspect_infinite_bench_passkey"
    name: "inspect infinite bench passkey"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "infinite_bench_passkey"
      evaluation_params: {}
      limit: 2
