suite_name: "Inspect Writing Evaluation Suite"
test_suite:

  # WritingBench
  - id: "inspect_writingbench"
    name: "inspect writingbench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    params:
      evaluation: "writingbench"
      evaluation_params: {
        "judge_model": "openai/gpt-4o",
      }
      limit: 2
