job_name: "RAG Base Query"
generation_jobs:
  - id: "rag_data_generation"
    name: "Rag Data Generation"
    image: "obsidian_data_generation_rag:latest"
    systems:
      generation_system: openai_gpt4o_mini
      simulator_system: openai_embedding
    volumes:
      input: input/
      output: output/
    params:
      output_dataset_path: "wf_123"
      chunk_size: 600
      chunk_overlap: 50
      num_questions: 2
      persona_name: "Customer"
      persona_description: "Customer of the Company"
    
    input_datasets:
      source_documents_pdf:
        file_path: "sample.pdf"
