systems:
  openai_gpt4o_mini:
      type: "llm_api"
      params:
        base_url: "http://localhost:4000/v1"
        model: "openai/gpt-4o-mini"
        api_key: "sk-1234"
  
  openai_embedding:
    type: "llm_api"
    params:
        base_url: "http://localhost:4000/v1"
        model: "openai/text-embedding-3-small"
        api_key: "sk-1234"
