systems:
  # --- Codex (OpenAI-compatible endpoint) ---
  # OPENAI_BASE_URL = <OAI compatible endpoint>
  # OPENAI_API_KEY = <API key>
  codex-oaic:
    type: "agent_cli"
    params:
      provider: "codex"
      model: "openai/gpt-4o-mini"
      base_url: "https://api.openai.com/v1"
      api_key: ${OPENAI_API_KEY}

  # --- Qwen Coder (OpenAI-compatible endpoint) ---
  # OPENAI_BASE_URL = <OAI compatible endpoint>
  # OPENAI_API_KEY = <API key>
  # qwen-coder-oaic:
  #   type: "agent_cli"
  #   params:
  #     provider: "qwen-coder" 
  #     model: deepseek/deepseek-v3.2
  #     base_url: "https://openrouter.ai/api/v1"
  #     api_key: ${OPENROUTER_API_KEY}

  # opencode-oaic:
  #   type: "agent_cli"
  #   params:
  #     provider: "opencode" 
  #     model: "openai/gpt-4o-mini"
  #     # base_url: "https://openrouter.ai/api/v1"
  #     api_key: ${OPENAI_API_KEY}

  # # https://block.github.io/goose/docs/getting-started/providers/
  # goose-oaic:
  #   type: "agent_cli"
  #   params:
  #     provider: "goose" 
  #     model: "openai/gpt-4o-mini"
  #     api_key: ${OPENAI_API_KEY}

  # # https://aider.chat/docs/llms.html
  # aider-oaic:
  #   type: "agent_cli"
  #   params:
  #     provider: "aider" 
  #     model: "openai/gpt-4o-mini"
  #     api_key: ${OPENAI_API_KEY}

  # cline-oaic:
  #   type: "agent_cli"
  #   params:
  #     provider: "cline-cli" 
  #     model: "openai:gpt-4o-mini"
  #     api_key: ${OPENAI_API_KEY}