name: Container Pipeline

on:
  push:
    branches: [main]
    tags:
      - "test_containers/*/*"
      - "sdg_containers/*/*"
  pull_request:
    branches: [main]

jobs:
  build-publish-test-containers:
    uses: ./.github/workflows/repo-containers-publish.yaml
    permissions:
      packages: write
      id-token: write
      contents: read
      attestations: write
    secrets: inherit
